**Part A**
1. Playerwise loyalty points collected on the following timeperiods:
a.2nd oct S1
b.16th oct S2
c.18th oct S1
d.26nd oct S2

In [7]:
import pandas as pd

file_path = '/content/Vindiata assignment/Playerwise Data for given dates.xlsx'
df = pd.read_excel(file_path)
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,a. 2nd October Slot S1,NaN,b. 16th October Slot S2,NaN,c. 18th October Slot S1,NaN,d. 26th October Slot S2,NaN
1,User ID,Total Points,User ID,Total Points,User ID,Total Points,User ID,Total Points
2,634,1478.354,634,1491.554,634,2723.098,714,2000.001
3,672,1300,212,999.991,208,1701.401,369,1501.915
4,566,1250.406,99,980.002,673,900.801,634,1237.01
...,...,...,...,...,...,...,...,...
636,75,0.2,NaN,NaN,NaN,NaN,NaN,NaN
637,59,0.2,NaN,NaN,NaN,NaN,NaN,NaN
638,46,0.2,NaN,NaN,NaN,NaN,NaN,NaN
639,41,0.2,NaN,NaN,NaN,NaN,NaN,NaN
640,19,0.2,NaN,NaN,NaN,NaN,NaN,NaN